name: Docker Publish Image

on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev

jobs:
    publish-image-in-docker-hub:
        runs-on: ubuntu-latest
        steps:
            - name: "Checkout application"
              uses: actions/checkout@v4 

            - name: "Login in Docker Hub"
              uses: docker/login-action@v3 
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: "Build and Push image"
              uses: docker/build-push-action@v5 
              with:
                context: .
                push: true
                tags: lucasanchietaamancio/api-cadastro:1.0.0